# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FamilyArchives' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FamilyArchives

  target 'FamilyArchivesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FamilyArchivesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
end
